baseURL = "http://testing-polly.s3-website-us-east-1.amazonaws.com"
languageCode = "en"
defaultContentLanguage="en"
title = "Testing Polly"
theme = "jane"
defaultContentLanguageInSubdir = true
uglyurls = true

[[menu.main]]             # config your menu              # 配置目录
  name = "This is Home"
  weight = 10
  identifier = "home"
  url = "/post/"
