baseURL = "http://testing-polly.s3-website-us-east-1.amazonaws.com"
languageCode = "en"
defaultContentLanguage="en"
title = "Testing Polly"
theme = "jane"
defaultContentLanguageInSubdir = true
uglyurls = true

[params]
  pollyMediaURL = "https://s3.us-east-1.amazonaws.com/testing-polly-polly-bucket"

[[menu.main]]             # config your menu              # 配置目录
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Posts"
  weight = 20
  identifier = "posts"
  url = "/post/"

[[menu.main]]
    name = "Begin"
    weight = 20
    identifier = "begin"
    url = "/begin/"
